# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88b7eee2a504313870fce8c1d6d09794d3a8de5baf1ab5413b28cb074bade2029b73154ae6ab0a75d03b89a3fe8da3138ac4d9df7aa4ba14961b16620ac38c52

test:
  secret_key_base: b83be51d0d11a6642bf684706d2f57e9f9302ac910b364d4482683954acca863172376a7d02fed1ea66dfea0740333521aa6b9abade72bff588f0b211c64f1be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
